### ISSUE TITLE
Tabs are not getting inactive after navigating to next tab.

### ISSUE THREAD

**Issue by shridharbennisur** [themre/react-closeable-tabs#1]
Active class is not getting removed for previous tabs on moving to next tabs, it keeps to be present for non-active tabs also hence making all tabs to be active state. Difficult to identify the current tab the user is viewing.

**Comment by themre** [comment]
thanks for the bug report. can you provide basic example on codesandbox.io ? it will be easier to see how you're using this lib, because i created option to have controlled and uncontrolled tabs and perhaps there is some case, where it doesn't work correct.

**Comment by shridharbennisur** [comment]
Hi, you can checkout sample example at  https://codesandbox.io/s/xrlyjjp9n4

**Comment by themre** [comment]
fixed. the issue was with new version of react since it keeps previous active class if you use AND operator. thanks for bug report! bump lib version and you're good to go.
