### ISSUE TITLE
onCloseTab not functioning on IE

### ISSUE THREAD

**Issue by saranmano** [themre/react-closeable-tabs#14]
Hello,

Could someone help?? tab close is not working in IE browser. IE version 11.  onTabClose() function not called. Could some one have a workaround for this. It is very urgent

Thanks!

**Comment by themre** [comment]
can you provide some info, some error stack? callback methods should work from IE9. maybe the error is what happens in callback.

**Comment by saranmano** [comment]
I don't get any errors. To debug I tried adding an alert on the method. The alert worked on chrome but not on IE and there are no errors.

 <CloseableTabs
                              tabPanelColor='white'
                              activeIndex={this.state.activeIndex}
                              data={this.state.data}
                              onCloseTab={this.callAlert}
                             />

**Comment by saranmano** [comment]
Ex:  <CloseableTabs
                              tabPanelColor='white'
                              activeIndex={this.state.activeIndex}
                              data={this.state.data}
                              onCloseTab={this.callAlert}/>

**Comment by themre** [comment]
Ah yes, `Object.values` is not present in IE. Use polyfill for this. Some might not want to s upport IE11 and I don't want to add additional polyfill to increase their size. Closing this issue, but will add this into README. Thx!

**Comment by saranmano** [comment]
I am sorry. polyfills support is already present. Still the issue is there. IE 11 is the one browser which the client uses.

**Comment by saranmano** [comment]
styled components could be a reason!! This library is a good one that perfectly fits the requirement, so i dont want to change it

**Comment by themre** [comment]
try also `Number.isInteger` polyfill, this also is missing in IE11.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

**Comment by saranmano** [comment]
Tried but no luck. :(

import "core-js";
import './polyfills';
import 'core-js/library/fn/object/values';
import 'core-js/library/fn/number/is-integer';
import "@babel/polyfill";
import 'core-js/es6/map';
import 'core-js/es6/set';

**Comment by themre** [comment]
just a quick question... can you downgrade to 1.1.2 version to see if there is something else? because i have a feeling this is only because Object.values and Number.isInteger are not working.

**Comment by saranmano** [comment]
Hello,

Ok. let me tell what I tried.

 I just had a method that creates an alert. This method was never called from IE but worked fine in chrome. I feel some css issue may be there with the close button. 

onTabClick() is fine. I made another alert on onTabClick(). At this time when I try to click the close 'X' button onTabClick event only was triggered but not onCloseTab(). 

< CloseableTabs
                              tabPanelColor='white'
                              activeIndex={this.state.activeIndex}
                              data={this.state.data}
                              onCloseTab={this.callAlert}
                              onTabClick={this.anotherAlert}  >

So I added another button in the Tab content and tried to remove the tab(updated the 'data' array in state) on click of the button and it worked perfectly fine in both browsers. 

So there wont be any issue with the callback but with the close button rendering. Initially I got error on IE browser console with styled component that property 'theme' was not found . I doubt could be here! not sure though

 _function (props) {
  return props.theme.primary ? props.theme.primary : '#00f';
});_

 So I added polyfill after which the error was gone . I thought this is still present and I do not have any errors in the console right now. 

Please help!

**Comment by themre** [comment]
hey, i published 1.1.5 version. the issue was with anchor being inside button which wouldn't fire. now i transformed `button` to regular `div`. please test it, thx!

**Comment by saranmano** [comment]
Many Thanks to you!! It works _/\_
