### ISSUE TITLE
After changing active index to 0 tab is not highlighting

### ISSUE THREAD

**Issue by shridharbennisur** [themre/react-closeable-tabs#2]
After setting active index to 0 first tab is not highlighting.
Attached sample example https://codesandbox.io/s/xplrjjoly4

**Comment by shridharbennisur** [comment]
Hi,
Its working for me after doing small change in componentWillReceiveProps
if (nextProps.activeIndex != -1) {
        newState.activeIndex = nextProps.activeIndex
 }

**Comment by themre** [comment]
It wasn't working because you are controlling the state from outside (CloseableTabsExample component). In this case, you need to handle props.
