### ISSUE TITLE
How to prevent unmount when opening new tabs?

### ISSUE THREAD

**Issue by Pa1sathvik** [themre/react-closeable-tabs#25]
Hey is there any option to prevent unmounting of the existing tab data when  opened new tab?

**Comment by Pa1sathvik** [comment]
Hey i got  it, Closing the issue.

**Comment by Pa1sathvik** [comment]
Closing the issue , noTabUnmount will help to resolve this.

**Comment by themre** [comment]
glad you found the solution :)
