### ISSUE TITLE
Is it possible to add tab using route

### ISSUE THREAD

**Issue by sinaislam** [themre/react-closeable-tabs#30]
From the left/side bar when user click on a link the component will be added as the new tab.

**Comment by themre** [comment]
You will just need to update state when you are passing tabs as prop. So add new tab when clicking some link and you should see new tab added. It might be best to create codesandbox example so I will see what exactly you try to achieve.

**Comment by sinaislam** [comment]
@themre , thank you for the quick response. I am very new to react and also at modern js. I will try to share what I am trying. So far it is a good addon. You can close this issue. Though it was not an issue rather a question.

**Comment by themre** [comment]
No problem, hope i helped a bit :) Best to learn is to reimplement some simple component and then see how things behave in React, otherwise you will run into some issues later.
